### ISSUE TITLE
 Final-capstone-back-end  Kanban Board 

### ISSUE THREAD

**Issue by XsidX** [developerwaleed/final-capstone-back-end#13]
> This is the [link](https://github.com/users/developerwaleed/projects/4) to the Kanban Board describing assigned back-end tasks.
>  This is the [link](https://github.com/users/developerwaleed/projects/3) to the issue describing assigned front-end tasks.

Team Members (5):
@OkoyeCharles (Member A)
@developerwaleed (Member B)
@OyePriscilla (Member C)
@abdulhamiid (Member D)
@XsidX (Member E)

**Front-end kanban**
![front-end-kanban](https://user-images.githubusercontent.com/41898352/203597085-5d6329a0-48ac-4f57-9459-5e7a92cfbae6.png)

B**ack-end kanban**
![back-end-kanban](https://user-images.githubusercontent.com/41898352/203597304-af191029-5b37-4fba-b8b8-7ba158b254ac.png)

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**Comment by OkoyeCharles** [comment]
Thanks @mcrd25
